import { StyleSheet, Dimensions } from 'react-native';


var styles = StyleSheet.create({
    saveStyle: {
      fontSize: 16,
      color: "#69BBD3"
    },
    lottie: {
      width: 300,
      height: 300
    },
    cameraButton: {
      paddingTop: 15,
      display: "flex",
      alignItems: "center",
      borderColor: "#00947A",
      bottom: 25,
      left: 167,
      borderWidth: 4,
      borderRadius: 50,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 85,
      height: 85,
    },
    contentButton: {
      paddingTop: 15,
      display: "flex",
      alignItems: "center",
      borderColor: "#69BBD3",
      bottom: 25,
      left: 167,
      borderWidth: 4,
      borderRadius: 50,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 85,
      height: 85,
    },
    crosshair: {
      position: 'absolute',
      top: (Dimensions.get('window').height / 2),
      left: 50,
      color: "white",
      fontSize: 50
    },
    userName: {
      position: 'absolute',
      top: (Dimensions.get('window').height / 2),
      left: 50,
      fontSize: 50,
      height: 50, 
      borderColor: 'gray',
      borderBottomWidth: 1,
      width: 250
    },
    password: {
      position: 'absolute',
      top: (Dimensions.get('window').height / 4),
      left: 50,
      fontSize: 50,
      height: 50, 
      borderColor: 'gray',
      borderBottomWidth: 1,
      width: 250
    },
    passwordConfirmation: {
      position: 'absolute',
      top: (Dimensions.get('window').height / 6),
      left: 50,
      fontSize: 50,
      height: 50, 
      borderColor: 'gray',
      borderBottomWidth: 1,
      width: 250
    },
    dragStyle: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderColor: "#69BBD3",
      top: 25,
      left: 10,
      borderWidth: 4,
      borderRadius: 35,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 60,
      height: 60,
    },
    plusStyle: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderColor: "#69BBD3",
      top: 300,
      left: 10,
      borderWidth: 4,
      borderRadius: 35,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 60,
      height: 60,
    },
    minusStyle: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderColor: "#69BBD3",
      top: 395,
      left: 10,
      borderWidth: 4,
      borderRadius: 35,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 60,
      height: 60,
    },
    saveButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderColor: '#69BBD3',
      bottom: 25,
      left: 345,
      borderWidth: 4,
      borderRadius: 35,
      position: 'absolute',
      backgroundColor: "rgba(0, 0, 0, 0)",
      width: 50,
      height: 50,
    },
  });


  export default styles;